### ISSUE TITLE
How did you find the docs for fields like "pegPriceType"?

### ISSUE THREAD

**Issue by vyorkin** [Lucsanszky/haskell-bitmex#16]
Looking at the source code I can see that you know the valid set of values for fields like "pegPriceType": https://github.com/Lucsanszky/haskell-bitmex/blob/fb299aec358f329dc01beacd0f05a0cbd6419522/rest/lib/BitMEX/API.hs#L1762

Could you please explain how did you find those values?

I've created a thread on reddit: https://www.reddit.com/r/BitMEX/comments/b1s56b/where_to_find_detailed_documentation_for_the_rest/

Thank you

**Comment by vyorkin** [comment]
Ah, nevermind, it is all there https://testnet.bitmex.com/api/explorer/#!/Order/Order_new

**Comment by Lucsanszky** [comment]
Sorry for the late response @vyorkin. I'm glad it has been resolved. 

Some further information regarding the REST API as a whole: it's auto-generated from a swagger spec.
However, I did do some modifications, detailed here: https://github.com/BitMEX/api-connectors/issues/118

**Comment by vyorkin** [comment]
thank you!
